# Generated by Django 3.0.2 on 2020-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun_sujet', models.CharField(max_length=50)),
                ('nom_scientifique_sujet', models.CharField(max_length=80)),
                ('nom_espece_sujet', models.CharField(max_length=50)),
                ('nom_compo', models.CharField(max_length=80)),
                ('description_sujet', models.TextField()),
                ('environnement_sujet', models.TextField()),
            ],
        ),
    ]
