# Generated by Django 3.0.2 on 2020-05-18 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('InChIKey', models.CharField(max_length=1000)),
                ('moleculeName', models.CharField(max_length=1000)),
                ('moleculeFormula', models.CharField(max_length=1000)),
                ('crcNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('molFileName', models.SlugField(max_length=100)),
                ('accurateMass', models.CharField(blank=True, max_length=100)),
                ('casNumber', models.SlugField(max_length=100)),
                ('compoundType', models.CharField(blank=True, max_length=1000)),
                ('opticalRotation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_web', models.URLField(blank=True)),
                ('signature', models.TextField(blank=True)),
                ('inscrit_newsletter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesName', models.CharField(max_length=1000)),
                ('publishedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('crcNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.Molecule')),
            ],
        ),
    ]
