# Generated by Django 3.0.2 on 2020-05-01 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id_alimentation', models.CharField(default='null', max_length=7, primary_key=True, serialize=False)),
                ('mode_alimentaire', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InChIKey', models.CharField(max_length=1000)),
                ('nom', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id_sujet', models.CharField(default='null', max_length=1000, primary_key=True, serialize=False)),
                ('nom_commun', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_web', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('signature', models.TextField(blank=True)),
                ('inscrit_newsletter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
