# Generated by Django 3.0.2 on 2020-05-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='crcNumber',
        ),
    ]
