# Generated by Django 3.0.2 on 2020-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alimentation',
        ),
        migrations.DeleteModel(
            name='Sujet',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='id',
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
