# Generated by Django 3.0.2 on 2020-02-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_auto_20200221_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='id',
        ),
        migrations.AddField(
            model_name='sujet',
            name='id_sujet',
            field=models.CharField(default='null', max_length=10, primary_key=True, serialize=False),
        ),
    ]
