# Generated by Django 3.0.2 on 2020-05-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_auto_20200514_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.Plante')),
            ],
        ),
    ]
