# Generated by Django 3.0.2 on 2020-05-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_remove_species_crcnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='crcNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='moleculeName',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
