# Generated by Django 3.0.2 on 2020-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='molecule_name',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
