# Generated by Django 3.0.2 on 2020-02-24 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0003_auto_20200223_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
