# Generated by Django 3.0.2 on 2020-02-24 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_auto_20200223_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id_alimentation', models.CharField(default='null', max_length=7, primary_key=True, serialize=False)),
                ('mode_alimentaire', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sujet',
            name='id_alimentation',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='acceuil.Alimentation'),
            preserve_default=False,
        ),
    ]
