# Generated by Django 3.0.2 on 2020-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_auto_20200514_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='molecule_name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom',
            field=models.CharField(max_length=300),
        ),
    ]
