# Generated by Django 3.0.2 on 2020-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_species_molecule'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='speciesName',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
