# Generated by Django 3.0.2 on 2020-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0005_auto_20200514_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='molecule_name',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom',
            field=models.CharField(max_length=1000),
        ),
    ]
