# Generated by Django 3.0.2 on 2020-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0005_auto_20200520_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='InChIKey',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='moleculeName',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='speciesName',
            field=models.CharField(max_length=10000),
        ),
    ]
