# Generated by Django 3.0.2 on 2020-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0006_auto_20200515_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
