# Generated by Django 3.0.2 on 2020-05-21 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0006_auto_20200520_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='publishedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
