# Generated by Django 3.0.2 on 2020-05-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0007_molecule_publisheddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
