# Generated by Django 3.0.2 on 2020-05-17 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0007_remove_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesName', models.CharField(max_length=1000)),
                ('moleculeName', models.CharField(max_length=1000)),
                ('publishedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Plante',
        ),
    ]
